### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by lssilva** [gnuhpc/Kafka-zk-restapi-UI#2]
Is the application in english ? or in chinese?

**Comment by gnuhpc** [comment]
Hi Issliva, we have managed to make the app i18n supported. There is a pr for this feature, however we have to resolve the conflict before getting it merged into master branch. I'll be back to you when it got done.

**Comment by gnuhpc** [comment]
I have merged all the commits about i18n. This version is able to support English. You could give it a try. Any suggestions and feedbacks are welcomed.

Thank you and close the issue.
